version: '3.9'

services:

  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - lab-net

  api-auth:
    image: alpine
    container_name: api-auth
    command: sh -c "while true; do echo 'api-auth running'; sleep 60; done"
    networks:
      - lab-net

networks:
  lab-net:
    driver: bridge
